---
title: "Final Project"
output: pdf_document
---

```{r setup, include=FALSE}
library(TCGAbiolinks)
library(tidyverse)
library(SummarizedExperiment)
library(DescTools)
library(qqman)
```


## Data Download, Cleaning, and Processing:

```{r}
query_meth.hg19 <- GDCquery(project= "TCGA-KIRC",
                            data.category = "DNA methylation",
                            platform = "Illumina Human Methylation 450",
                            legacy = TRUE)
GDCdownload(query_meth.hg19)
data.hg19 <- GDCprepare(query_meth.hg19)

meth_data = data.frame(assay(data.hg19))

## Assessing Whether Samples are Paired or Not:
 patients = data.frame(Patient_ID = data.hg19$patient, Barcode = data.hg19$barcode)
 
split = data.frame(table(patients$data.hg19.patient))

split = data.frame(table(patients$Patient_ID))

split = merge(split,patients,by.x = "Var1",by.y="Patient_ID")

sample = data.frame(data.hg19$sample_type,data.hg19$patient,data.hg19$barcode,split$Freq)

colnames(sample) = c("Group","Patient","Sample_ID","Paired")

sample$Group = recode(sample$Group, "Additional - New Primary" = "Primary Tumor")

Case = filter(sample, Group == "Primary Tumor")

Case$Sample_ID = gsub("-",".",Case$Sample_ID)

Control = filter(sample, Group == "Solid Tissue Normal")

Control$Sample_ID = gsub("-",".",Control$Sample_ID)

Case_Meth_Data = dplyr::select(meth_data,tidyselect::contains(Case$Sample_ID))

Control_Meth_Data = dplyr::select(meth_data,tidyselect::contains(Control$Sample_ID))

Case_Meth_Data = data.frame(t(Case_Meth_Data))

Control_Meth_Data = data.frame(t(Control_Meth_Data))

Case_Meth_Data = Case_Meth_Data[, colSums(is.na(Case_Meth_Data)) != nrow(Case_Meth_Data)]

Control_Meth_Data = Control_Meth_Data[, colSums(is.na(Control_Meth_Data)) != nrow(Control_Meth_Data)]

table(colnames(Case_Meth_Data)==colnames(Control_Meth_Data)) #check if CpG sites are same

# Add information about sample pairing to meth data:

Case_Meth_Data$Patient = Case$Patient

Control_Meth_Data$Patient = Control$Patient
```

## Two Sample and Paired T-Tests:

```{r}
#Two Sample T tests for Cases and Controls for Each CpG Site:

paired_t_test_res = data.frame()

t_test_res = data.frame()

Case_Idep_Meth_Data = filter(Case_Meth_Data,!Patient%in%Control_Meth_Data$Patient)

#Control_Idep_Meth_Data = filter(Control_Meth_Data,!Patient%in%Case_Meth_Data$Patient)

Case_Paired_Meth_Data = filter(Case_Meth_Data,Patient%in%Control_Meth_Data$Patient)

Control_Paired_Meth_Data = filter(Control_Meth_Data,Patient%in%Case_Meth_Data$Patient)

##Paired T Tests:

Case_Paired_Meth_Data = dplyr::select(Case_Paired_Meth_Data,-c(396066,306067))


Control_Paired_Meth_Data = dplyr::select(Control_Paired_Meth_Data,-c(396066,306067))

Paired_Combined_Meth_Data$Group = c(rep("Case",160),rep("Control",160))

for (j in seq(1,ncol(Case_Paired_Meth_Data))){
    paired_t_test_res_temp = t.test(Case_Paired_Meth_Data[[j]],Control_Paired_Meth_Data[[j]],alternative="two.sided",paired=T)%>%
      broom::tidy()
    paired_t_test_res = rbind(paired_t_test_res,paired_t_test_res_temp) 
}

paired_t_test_res$CpG_Site = colnames(Case_Paired_Meth_Data)

paired_t_test_res = dplyr::select(paired_t_test_res,c("CpG_Site","p.value"))

## FDR Correction:

paired_t_test_res_FDR = paired_t_test_res%>%
  mutate(FDR_P_Value = p.adjust(paired_t_test_res$p.value,method="fdr"))

##Two Sample T Tests:

for (j in seq(1,ncol(Case_Idep_Meth_Data))){
    t_test_res_temp = t.test(Case_Idep_Meth_Data[[j]],Control_Meth_Data[[j]],alternative="two.sided")%>%
      broom::tidy()
    t_test_res = rbind(t_test_res,t_test_res_temp) 
}

t_test_res$CpG_Site = colnames(Case_Idep_Meth_Data)

t_test_res = dplyr::select(t_test_res,c("CpG_Site","p.value"))

## FDR Correction:

t_test_res_FDR = t_test_res%>%
  mutate(FDR_P_Value = p.adjust(t_test_res$p.value,method="fdr"))
```

## Logistic Regression:

```{r}

```

## Results:

```{r}
## Number of Methylation Sites with Significant Difference between Case and Controls:

## Manhattan Plot of FDR Corrected P-Values from Paired T Tests:

chrom_info = data.frame(rowRanges(data.hg19))%>%
  dplyr::select("seqnames","start","probeID")

t_test_FDR_w_chrom = merge(paired_t_test_res_FDR,chrom_info,by.x="CpG_Site",by.y="probeID")

colnames(t_test_FDR_w_chrom) = c("CpG_Site","p.value","FDR_P_Value",
                                 "chrom","pos")

t_test_FDR_w_chrom$FDR_P_Value = -log10(t_test_FDR_w_chrom$FDR_P_Value)

t_test_FDR_w_chrom$chrom = gsub("chr","",t_test_FDR_w_chrom$chrom)

t_test_FDR_w_chrom$chrom = recode(t_test_FDR_w_chrom$chrom,"X" = "23","Y"="24","NA"="25")

t_test_FDR_w_chrom$chrom = as.numeric(t_test_FDR_w_chrom$chrom)

plot <- t_test_FDR_w_chrom %>% 
  group_by(chrom) %>% 
  summarise(chr_len=max(pos)) %>% 
  mutate(tot=cumsum(as.numeric(chr_len))-chr_len) %>%
  dplyr::select(-chr_len) %>%
  left_join(t_test_FDR_w_chrom, ., by=c("chrom"="chrom")) %>%
  arrange(chrom,pos) %>%
  mutate(pos_cum=pos+tot)

axisdf = plot %>% group_by(chrom) %>% summarize(center=( max(pos_cum) + min(pos_cum) ) / 2 )

axisdf$chrom = c(seq(1,22),"X","Y","MT")

ggplot(plot, aes(x=pos_cum, y=FDR_P_Value)) +
    geom_point( aes(color=as.factor(chrom)), alpha=0.8, size=1.3) +
    scale_color_manual(values = rep(c("grey", "skyblue"),25))+
    scale_x_continuous( label = axisdf$chrom[seq(1, length(axisdf$chrom), by = 2)], breaks= axisdf$center[seq(1, length(axisdf$center), by = 2)] ) +
    scale_y_continuous(expand = c(0, 0) ) +
    theme_bw() +
    theme( 
      legend.position="none",
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    )+
  xlab("Chromosome")+
  ylab("-log10(FDR Corrected P-value)")+
  ggtitle("Manhattan Plot for Paired T Test Samples with FDR Correction")

## Manhattan Plot of FDR Corrected P-Values from Two Sample T Tests:

chrom_info = data.frame(rowRanges(data.hg19))%>%
  dplyr::select("seqnames","start","probeID")

t_test_FDR_w_chrom = merge(t_test_res_FDR,chrom_info,by.x="CpG_Site",by.y="probeID")

colnames(t_test_FDR_w_chrom) = c("CpG_Site","p.value","FDR_P_Value",
                                 "chrom","pos")

t_test_FDR_w_chrom$FDR_P_Value = -log10(t_test_FDR_w_chrom$FDR_P_Value)

t_test_FDR_w_chrom$chrom = gsub("chr","",t_test_FDR_w_chrom$chrom)

t_test_FDR_w_chrom$chrom = recode(t_test_FDR_w_chrom$chrom,"X" = "23","Y"="24","NA"="25")

t_test_FDR_w_chrom$chrom = as.numeric(t_test_FDR_w_chrom$chrom)

plot <- t_test_FDR_w_chrom %>% 
  group_by(chrom) %>% 
  summarise(chr_len=max(pos)) %>% 
  mutate(tot=cumsum(as.numeric(chr_len))-chr_len) %>%
  dplyr::select(-chr_len) %>%
  left_join(t_test_FDR_w_chrom, ., by=c("chrom"="chrom")) %>%
  arrange(chrom,pos) %>%
  mutate(pos_cum=pos+tot)

axisdf = plot %>% group_by(chrom) %>% summarize(center=( max(pos_cum) + min(pos_cum) ) / 2 )

axisdf$chrom = c(seq(1,22),"X","Y","MT")

ggplot(plot, aes(x=pos_cum, y=FDR_P_Value)) +
    geom_point( aes(color=as.factor(chrom)), alpha=0.8, size=1.3) +
    scale_color_manual(values = rep(c("grey", "skyblue"),25))+
    scale_x_continuous( label = axisdf$chrom[seq(1, length(axisdf$chrom), by = 2)], breaks= axisdf$center[seq(1, length(axisdf$center), by = 2)] ) +
    scale_y_continuous(expand = c(0, 0) ) +
    theme_bw() +
    theme( 
      legend.position="none",
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    )+
  xlab("Chromosome")+
  ylab("-log10(FDR Corrected P-value)")+
  ggtitle("Manhattan Plot for Two Sample T Test Samples with FDR Correction")
```

## Discussion and Conclusions:
